@localUrl = http://localhost:3000/graphql
@qaUrl = https://m7g5pc0boi.execute-api.us-east-1.amazonaws.com/dev/graphql
@AuthToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imtvb2xndXlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJrb29sZ3V5MTEyIiwidXNlcl9pZCI6IjEiLCJyb2xlIjpbIlVTRVIiXSwiaWF0IjoxNTQ3MjYzNjgxLCJleHAiOjE1NDczNTAwODF9.VTXsW3V-qtcVZGiVz-AJViPW67THqlsz8JzBGhVVz1s
POST {{qaUrl}}
Content-Type: application/json

{
    "query": "{\n hello \n}\n"
}

#####################################################################################################################
# curl -X POST -H "Content-Type:application/json" https://o6b8ejudj2.execute-api.us-east-1.amazonaws.com/dev/graphql --data '{"query":"mutation {\n  createHabit(user_id: \"123\", input: {habit_id: \"321\", user_id: \"123\", created_at: \"now\", name: \"LEARN GRAPHQL\", type: [\"React.js\", \"Front-end\", \"Frontend?\", \"Front end?\"]}) {\n    name\n    type\n  }\n}\n"}'
# Create habit
POST {{qaUrl}}
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
    "query":"mutation {\n  createHabit(input: {habit_id: \"234234234\", created_at: \"later\", name: \"nice\", type: \"Apollo\"}) {\n    name\n    type\n  }\n}\n"
}

#####################################################################################################################
# Get created habit
POST {{qaUrl}}
Content-Type: application/json

{
    "query": "{\n  getHabit(habit_id: \"321\", created_at: \"now\") {\n    name\n  }\n}\n"
}

#####################################################################################################################
# Get All Habits (dynamodb scan method)
POST {{qaUrl}}
Content-Type: application/json

{
    "query":"{\n  getAllHabits(user_id: \"123\") {\n    name\n    user_id\n    habit_id\n    created_at\n  }\n}\n"
}

#####################################################################################################################
# Delete habit we first created
POST {{qaUrl}}
Content-Type: application/json

{
    "query":"mutation {\n  deleteHabit(habit_id: \"321\", created_at: \"now\") {\n    name\n    type\n  }\n}\n"
}


#####################################################################################################################
# query for getting user data
POST {{qaUrl}}
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
    "query":"{\n  me {\n    user_id\n    username\n  }\n}\n"
}

#####################################################################################################################
# signup test
POST {{qaUrl}}
Content-Type: application/json

{
    "query":"mutation {\n  signup(input: {id: \"1\", username: \"koolguy112\", email: \"koolguy@gmail.com\", password: \"111\", created_at: \"now\"})\n}\n"
}

#####################################################################################################################
# login test
POST {{qaUrl}}
Content-Type: application/json

{
    "query":"mutation {\n  login(email: \"email@email.com\", password: \"12345678\")\n}\n"
}

#####################################################################################################################
# query for getting user data
POST {{qaUrl}}
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
    "query":"{\n  getHabits{\n    name\n   type\n}\n}\n"
}