POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "{\n hello \n}\n"
}

###
POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "{\n  getHabit(user_id: \"1543011106394\", habit_id: \"f6d0f1fc-5c65-464a-9d46-6895737efdfe\") {\n    name\n  }\n}\n"
}

