name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: setup to use npm and deploy w/ serverless
      run: |
        npm install
        npm install -g serverless
    - name: Deploy to serverless
      env: 
        NODE_ENV: dev
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIST_SECRET: ${{ secrets.REDIS_SECRET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        serverless deploy | tee deploy.out
